local prefix = "<leader>u"
return {
  "xiyaowong/transparent.nvim",
  lazy = false,
  opts = {
    -- table: default groups
    groups = {
      "Normal",
      "NormalNC",
      "Comment",
      "Constant",
      "Special",
      "Identifier",
      "Statement",
      "PreProc",
      "Type",
      "Underlined",
      "Todo",
      "String",
      "Function",
      "Conditional",
      "Repeat",
      "Operator",
      "Structure",
      "LineNr",
      "NonText",
      "SignColumn",
      "CursorLineNr",
      "EndOfBuffer",
			"Float",
			"NormalFloat",
			"FloatBorder",
			"FloatermBorder",
			"NeoTreeFloatBorder",
			"NeoTreeFloatTitle",
			"NeoTreeFloatNormal",
			"TelescopeBorder",
			"SignColumn",
			"GitSignsAdd",
			"GitSignsChange",
			"GitSignsDelete",
			"GitSignsTopDelete",
			"GitSignsUntracked",
			"DiagnosticSignError",
			"DiagnosticSignHint",
			"DiagnosticSignInfo",
			"DiagnosticSignWarn",
			"LineNr",
			"CursorLineNr",
			"TablineSel",
			"FoldColumn"
    },
    -- table: additional groups that should be cleared
    extra_groups = {
      "NormalFloat",
      "NvimTreeNormal",
      "NeoTreeNormal",
      "NeoTreeFloatBorder",
      "NeoTreeNormalNC",
    },
    -- table: groups you don't want to clear
    exclude_groups = {},
  },
  keys = {
    { prefix .. "T", "<cmd>TransparentToggle<CR>", desc = "Toggle transparency" },
  },
}
